const GlobalEnum = {
  Route: {
    MAIN_SCENE: 'MAIN_SCENE',
    ARTICLE_LIST: 'ARTICLE_LIST',
    ARTICLE_DETAIL: 'ARTICLE_DETAIL',
    ARTICLE_NEWS: 'ARTICLE_NEWS',
    ALARM_SETTING: 'ALARM_SETTING',
    PDF_SCENE: 'PDF_SCENE',
    MAP_SCENE: 'MAP_SCENE',
    IMAGE_WEBVIEW_SCENE: 'IMAGE_WEBVIEW_SCENE',
  },
};

export default GlobalEnum;
